services:
  postgres:
    image: postgres:16
    container_name: identity_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identityDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  identityservice:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: identity_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 5000
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=identityDb;Username=postgres;Password=postgres"
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data: